# Generated by Django 5.0.2 on 2024-02-19 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="big_integer_field",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="binary_field",
            field=models.BinaryField(default=b"\x00"),
        ),
        migrations.AddField(
            model_name="student",
            name="boolean_field",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="char_field",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="date_field",
            field=models.DateField(default=datetime.date(2024, 2, 19)),
        ),
    ]
