# Generated by Django 5.0.2 on 2024-02-22 05:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0002_student_big_integer_field_student_binary_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_time_field",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="decimal_field",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="student",
            name="duration_field",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name="student",
            name="email_field",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="file_field",
            field=models.FileField(default="", upload_to="files/"),
        ),
        migrations.AddField(
            model_name="student",
            name="float_field",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="student",
            name="generic_ip_address_field",
            field=models.GenericIPAddressField(default="0.0.0.0"),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_field",
            field=models.DateField(default=datetime.date(2024, 2, 22)),
        ),
    ]
